### ISSUE TITLE
Error While Staking NFT's using GEM NFT

### ISSUE THREAD

**Issue by Abubakar672** [gemworks/gem-farm#124]
**ERROR:**

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1785 
    Program farmL4xeBFVXJqtfxCzU9b28QACM7E2W2ctT6epAjvE invoke [1]
    Program log: Instruction: Stake
    Program log: stake

**Comment by aabdullah29** [comment]
**I am also facing the same issue while staking the new gem(NFT) and got 2 errors on the console:**

**Error 1:**
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1785 
    Program farmL4xeBFVXJqtfxCzU9b28QACM7E2W2ctT6epAjvE invoke [1]
    Program log: Instruction: Stake
    Program log: stake
    Program log: AnchorError thrown in programs/gem_farm/src/instructions/stake.rs:80. Error Code: VaultIsEmpty. Error Number: 6021. Error Message: vault doesnt't containt any gems.
    Program farmL4xeBFVXJqtfxCzU9b28QACM7E2W2ctT6epAjvE consumed 34628 of 200000 compute units
    Program farmL4xeBFVXJqtfxCzU9b28QACM7E2W2ctT6epAjvE failed: custom program error: 0x1785


**Error 2:**
Error: AnchorError thrown in programs/gem_farm/src/instructions/stake.rs:80. Error Code: VaultIsEmpty. Error Number: 6021. Error Message: vault doesnt't containt any gems.
    at wt.parse (index.js:1:11565)
    at Mt (index.js:1:12745)
    at yr._rpcFn (index.js:16:37567)
