### ISSUE TITLE
Staking Error: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1 (Plenty of SOL in wallet)

### ISSUE THREAD

**Issue by BungeeDesign** [gemworks/gem-farm#29]
I'm getting a "Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1" 

Staking has been working fine. Been getting this error today? I've got enough funds in the wallet I'm using to stake the NFT? 

Using the gem-farm deployed on Mainnet.

> Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1 
    Program bankHHdqMuaaST4qQk6mkzxGeKPHWmqdgor6Gs8r88m invoke [1]
    Program log: Instruction: DepositGem
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3297 of 175156 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: Transfer
    Program log: Error: insufficient funds
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2135 of 146292 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program error: 0x1
    Program bankHHdqMuaaST4qQk6mkzxGeKPHWmqdgor6Gs8r88m consumed 55843 of 200000 compute units
    Program bankHHdqMuaaST4qQk6mkzxGeKPHWmqdgor6Gs8r88m failed: custom program error: 0x1
sendEncodedTransaction @ index.browser.esm.js:7051
await in sendEncodedTransaction (async)
sendRawTransaction @ index.browser.esm.js:7014
Eo @ index.browser.esm.js:8977
send @ provider.js:82
await in send (async)
i @ rpc.js:9
(anonymous) @ gem-bank.client.js:379
s @ gem-bank.client.js:24
Promise.then (async)
u @ gem-bank.client.js:26
s @ gem-bank.client.js:24
Promise.then (async)
u @ gem-bank.client.js:26
s @ gem-bank.client.js:24
Promise.then (async)
u @ gem-bank.client.js:26
s @ gem-bank.client.js:24
Promise.then (async)
u @ gem-bank.client.js:26
(anonymous) @ gem-bank.client.js:27
s @ gem-bank.client.js:23
depositGem @ gem-bank.client.js:351
(anonymous) @ index.ts:81
d @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
a @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
a @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
a @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
a @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
t @ index.ts:32
(anonymous) @ Vault.vue?4b75:364
d @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
a @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Vault.vue?4b75:358
(anonymous) @ Vault.vue?4b75:186
d @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
a @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Vault.vue?4b75:184
(anonymous) @ Vault.vue?4b75:318
eo @ runtime-core.esm-bundler.js:6708
to @ runtime-core.esm-bundler.js:6717
m @ runtime-core.esm-bundler.js:7125
Ao @ runtime-core.esm-bundler.js:6881
Eo @ runtime-core.esm-bundler.js:6922
Promise.then (async)
vo @ runtime-core.esm-bundler.js:6838
ko @ runtime-core.esm-bundler.js:6860
So @ runtime-core.esm-bundler.js:6863
Io.y @ runtime-core.esm-bundler.js:7153
C @ reactivity.esm-bundler.js:358
B @ reactivity.esm-bundler.js:346
(anonymous) @ reactivity.esm-bundler.js:472
e.<computed> @ reactivity.esm-bundler.js:398
x @ Vault.vue?4b75:175
Object.default.Object.onClick.t.<computed>.t.<computed> @ Vault.vue?c9c7:45
eo @ runtime-core.esm-bundler.js:6708
to @ runtime-core.esm-bundler.js:6717
n @ runtime-dom.esm-bundler.js:357
rpc.js:13 Translating error Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at eo.sendEncodedTransaction (index.browser.esm.js:7055:13)
    at async eo.sendRawTransaction (index.browser.esm.js:7014:11)
    at async Eo (index.browser.esm.js:8977:9)
    at async o.send (provider.js:82:15)
    at async Object.i [as depositGem] (rpc.js:9:23)

**Comment by BungeeDesign** [comment]
Fixed by updating to the latest SDK.
